language: node_js
node_js:
- '13'
sudo: false
notifications:
  email:
    recipients:
    - steven@stevenweaver.org
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - develop
  - 1.0.0-alpha

cache:
  yarn: true
  directories:
  - ".eslintcache"
  - node_modules
  
script:
  - yarn test
